movie_sparql/urls.py
from django.conf.urls import url
from django.contrib import admin

from web.views import SearchView, MovieView, ContributorView, GenreView

urlpatterns = [
    url(r'^search$', SearchView.as_view(), name='search'),
    url(r'^movie/(?P<name>[\w\d\s]+)$', MovieView.as_view(), name='movie-detail'),
    url(r'^contributor/(?P<name>[\w\d\s]+)$', ContributorView.as_view(), name='contributor-detail'),
    url(r'^genre/(?P<name>[\w\d\s]+)$', GenreView.as_view(), name='genre-detail'),
    url(r'^admin/', admin.site.urls),
]

web/models.py
from django.db import models


class Movie(models.Model):
    name = models.CharField(max_length=128)
    contributors = models.ManyToManyField(to='Contributor', related_name='movies')

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=128)

    @property
    def related_movies(self):
        return Movie.objects.filter(contributors__genre=self).distinct()

    def __str__(self):
        return self.name


class Contributor(models.Model):
    name = models.CharField(max_length=128)
    genre = models.ForeignKey(to=Genre, related_name='contributors')

    def __str__(self):
        return self.name

web/forms.py
from django import forms


class SearchForm(forms.Form):
    movie_name = forms.CharField(max_length=128)

web/views.py
from django.http import HttpResponseRedirect

from django.urls import reverse
from django.views.generic import FormView, TemplateView

from movie_sparql.query import get_movie
from web.forms import SearchForm
from web.models import Movie, Contributor, Genre


class SearchView(FormView):
    template_name = 'web/search.html'
    form_class = SearchForm

    def form_valid(self, form):
        """
        If the form is valid, query db and persist data
        """
        movie_obj = get_movie("Asturias")  # form.data['movie_name'])

        # TODO get_or_create contibutors, genres

        movie, created = Movie.objects.get_or_create(name=movie_obj["name"])
        return HttpResponseRedirect(reverse('movie-detail', kwargs={'name': movie.name}))


class MovieView(TemplateView):
    template_name = 'web/movie.html'

    def get_context_data(self, **kwargs):
        kwargs.update({'object': Movie.objects.get(name=kwargs["name"])})
        return super().get_context_data(**kwargs)


class ContributorView(TemplateView):
    template_name = 'web/contributor.html'

    def get_context_data(self, **kwargs):
        kwargs.update({'object': Contributor.objects.get(name=kwargs["name"])})
        return super().get_context_data(**kwargs)


class GenreView(TemplateView):
    template_name = 'web/genre.html'

    def get_context_data(self, **kwargs):
        kwargs.update({'object': Genre.objects.get(name=kwargs["name"])})
        return super().get_context_data(**kwargs)

web/templates/web/contributor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contributor detail</title>
</head>
<body>
    <h3>Contributor {{ object.name }} detail</h3>
    <table border="1">
        <thead>
        <tr>
           <td>Movie</td>
        </tr>
        </thead>
        {% for movie in object.movies.all %}
            <tr>
                <td><a href="{% url "movie-detail" name=movie.name %}">{{ movie.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

web/templates/web/genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genre detail</title>
</head>
<body>
    <h3>Genre {{ object.name }} detail</h3>
    <table border="1">
        <thead>
        <tr>
           <td>Contributors playing in this genre</td>
        </tr>
        </thead>
        {% for contributor in object.contributors.all %}
            <tr>
                <td><a href="{% url "contributor-detail" name=contributor.name %}">{{ contributor.name }}</a></td>
            </tr>
        {% endfor %}
    </table>

    <br />

    <table style="border: 1">
        <thead>
        <tr>
           <td>Movies with soundtrack in this genre</td>
        </tr>
        </thead>
        {% for movie in object.related_movies %}
            <tr>
                <td><a href="{% url "movie-detail" name=movie.name %}">{{ movie.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

web/templates/web/movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie detail</title>
</head>
<body>
    <h3>Movie {{ object.name }} detail</h3>
    <table border="1">
        <thead>
        <tr>
           <td>Music Contributor</td>
           <td>Genre</td>
        </tr>
        </thead>
        {% for contributor in object.contributors.all %}
            <tr>
                <td><a href="{% url "contributor-detail" name=contributor.name %}">{{ contributor.name }}</a></td>
                <td><a href="{% url "genre-detail" name=contributor.genre %}">{{ contributor.genre }}</a></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

web/templates/web/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    <form action="" method="post">
        <label for="id_movie_name">Movie name:</label>
        {{ form.movie_name }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</body>
</html>